resources:
  - vote-deployment.yaml
  - vote-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - worker-deployment.yaml
  - db-deployment.yaml
  - db-service.yaml
  - result-deployment.yaml
  - result-service.yaml

namespace: dev