apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 30000
      targetPort: 80
      protocol: TCP
      nodePort: 30000
  selector:
    app: vote