apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: schoolofdevops/vote:v12
        ports:
        - containerPort: 80